### ISSUE TITLE
Abonnement Topic

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#1]
Pour les utilisateurs avancés, la gestion des notification est très utile. Existe-t-il un moyen de le rendre disponible sans charger l'UI ?
<img width="600" alt="screen shot 2016-11-24 at 15 32 15" src="https://cloud.githubusercontent.com/assets/1053676/20601916/47f5d9c0-b25b-11e6-9e80-630c86c16495.png">

**Comment by ekkans** [comment]
Je les affiche à nouveau sur la pré-prod, sous la forme ci-dessous pour l'instant, mais donc @MarzChew cela te permet de modifier le css directement via l'admin

![screenshot 2016-12-01 13 31 24](https://cloud.githubusercontent.com/assets/88243/20794089/9dfd9730-b7ca-11e6-84a9-bb27a382b30b.png)

**Comment by bedhed** [comment]
Merci, je pense que nous devons en parler tout d'abord.
C'est surtout sur les catégories que la feature est importante.
++

**Comment by discolaura** [comment]
Oui ! # Point prio
@bedhed

**Comment by bedhed** [comment]
À voir avec @MarzChew qui doit voir comment ça se passe sur la verion par défaut.
