### ISSUE TITLE
Menu notification infini

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#11]
Très souvent le menu est infini et le bouton "toutes les notifs" est inaccessible.
<img width="330" alt="screen shot 2016-11-29 at 11 51 58" src="https://cloud.githubusercontent.com/assets/1053676/20707074/69ae3346-b62a-11e6-80bf-3576bdf96c20.png">

**Comment by jeremie-baboukhian** [comment]
Priorité haute

**Comment by ekkans** [comment]
Normalement c'est bon maintenant
