### ISSUE TITLE
Contraste Auteur/Titre dans notifications

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#12]
On ne fait pas la différence entre l'auteur et le titre du topic.
Now,
<img width="327" alt="screen shot 2016-11-29 at 11 52 26" src="https://cloud.githubusercontent.com/assets/1053676/20707113/8b5b4de4-b62a-11e6-855b-918ffffbc768.png">
Charte p.20
<img width="345" alt="screen shot 2016-11-29 at 11 54 53" src="https://cloud.githubusercontent.com/assets/1053676/20707214/cc7b82c6-b62a-11e6-98ca-004fa194b292.png">
Original
<img width="313" alt="screen shot 2016-11-29 at 11 52 34" src="https://cloud.githubusercontent.com/assets/1053676/20707114/8b5c59aa-b62a-11e6-8747-39c59b92a6d0.png">

**Comment by ekkans** [comment]
J'ai amélioré ça :)

![screenshot 2016-12-01 12 22 31](https://cloud.githubusercontent.com/assets/88243/20792222/fa36675c-b7c0-11e6-993c-c4bcd036364a.png)

**Comment by bedhed** [comment]
:+1:
À voir si on veut pas faire un peu plus.

**Comment by jeremie-baboukhian** [comment]
Chez moi cette feature ne fonctionne pas. (les notifs ne changent jamais)

**Comment by ekkans** [comment]
Tes nouvelles notifications ne sont pas en bleu @MarzChew ? (avec une classe css *read* ?)

**Comment by jeremie-baboukhian** [comment]
Ca c'est good mais j'ai jamais de nouvelle notifs j'ai l'impression.
Depuis le 18 septembre je n'en ai reçu aucune mais peut-être est-ce normal ?

**Comment by ekkans** [comment]
C'est probablement normal @MarzChew – tu peux peut-être créer un sujet et je vais y répondre pour que tu reçoives une notification

**Comment by jeremie-baboukhian** [comment]
https://forums.laruchequiditoui.fr/t/test-hello-world/697

Il me semble que francois m'avait fait un retour un peu similaire

**Comment by ekkans** [comment]
Je t'ai répondu @MarzChew – mais je pense que tu devrais faire le test sur la pré-prod plutôt

**Comment by jeremie-baboukhian** [comment]
J'ai delete le message, j'ai bien recu la notif :)

**Comment by jeremie-baboukhian** [comment]
update du css
