### ISSUE TITLE
Contraste Lu/Non Lu dans les notifications

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#13]
Le bouton "Voir toutes" doit être sur du blanc.
Now
<img width="322" alt="screen shot 2016-11-29 at 11 52 10" src="https://cloud.githubusercontent.com/assets/1053676/20707267/068efa6a-b62b-11e6-8968-77d2beb487d5.png">
Design
<img width="345" alt="screen shot 2016-11-29 at 11 54 53" src="https://cloud.githubusercontent.com/assets/1053676/20707273/0bf6dc52-b62b-11e6-9f36-6ea63f00cc0a.png">

**Comment by jeremie-baboukhian** [comment]
My mistake. Je vais itérer ca.

**Comment by bedhed** [comment]
@MarzChew c'est juste chez toi. Y'a juste le CSS à corriger.

**Comment by ekkans** [comment]
My mistake ^^ c'est corrigé :)

**Comment by bedhed** [comment]
:+1:
