### ISSUE TITLE
Date, nickname et nom sur Topic

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#14]
Now
<img width="710" alt="screen shot 2016-11-29 at 11 59 30" src="https://cloud.githubusercontent.com/assets/1053676/20707354/60963cf8-b62b-11e6-9314-1ecd994d692c.png">

Charte p.63 + Nickname à rajouter (ou remplacer par Nickname si pas de nom)
<img width="353" alt="screen shot 2016-11-29 at 11 59 34" src="https://cloud.githubusercontent.com/assets/1053676/20707357/6484917a-b62b-11e6-926d-217882c4bd8c.png">

**Comment by ekkans** [comment]
En fait dans mes préférences, mon nom était *sbourdu*. Je viens de mettre mon nom complet :

![screenshot 2016-12-01 12 19 26](https://cloud.githubusercontent.com/assets/88243/20792122/84130620-b7c0-11e6-9bbd-681372cde3c8.png)

**Comment by bedhed** [comment]
Compris.
Le SSO apporte le Nom complet, donc on est bon.
:+1:
