### ISSUE TITLE
Afficher pin dans topic list

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#15]
On voit bien le pin sur le topic
<img width="733" alt="screen shot 2016-11-29 at 12 03 45" src="https://cloud.githubusercontent.com/assets/1053676/20707503/0012ccd8-b62c-11e6-8b1a-4c646a61dfea.png">

Mais pas dans la liste
<img width="675" alt="screen shot 2016-11-29 at 12 03 50" src="https://cloud.githubusercontent.com/assets/1053676/20707511/056c29a4-b62c-11e6-9281-f0275228be3f.png">

**Comment by jeremie-baboukhian** [comment]
Tu veux dire sur le feed de la home ?

**Comment by bedhed** [comment]
Yes.

**Comment by ekkans** [comment]
C'est fait :)

![screenshot 2016-12-14 19 23 19](https://cloud.githubusercontent.com/assets/88243/21195158/ed588bb0-c232-11e6-8c2a-f2565a38360f.png)
