### ISSUE TITLE
Header de Topic

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#16]
On a 1 catégories qu'on veut voir.
Peut-être une sous-catégorie, qu'on veut voir si jamais elle est là.
Et des tags, qu'on veut voir, mais beaucoup moins.
<img width="730" alt="screen shot 2016-11-29 at 12 05 58" src="https://cloud.githubusercontent.com/assets/1053676/20707662/97897f26-b62c-11e6-8e8f-0b8b7b542cef.png">

Ne pas oublier le mode wiki, et le mousehover sur le nombre de versions.
<img width="304" alt="screen shot 2016-11-29 at 12 40 34" src="https://cloud.githubusercontent.com/assets/1053676/20708633/251bdd12-b631-11e6-9612-5424b14cee12.png">

**Comment by jeremie-baboukhian** [comment]
Je serais d'avis de privilégier la catégorie parent du poste (niveau **n**) à savoir garder uniquement une catégorie (pas de catégorie parente d'un catégorie pas de **n-1** ).
Concernant les tags, sauf erreur de ma part il a été décidé de les laisser pour les super admins et pour assurer une compatibilité avec les anciens postes. Dans cette optique et comme convenu précédemment le nouvel éditeur ne permettra pas d'ajouter des tags. 
À l'usage donc on pourrait ne les afficher que pour les super admins ou même pas du tout.

**Comment by jeremie-baboukhian** [comment]
Je rajouterais une task pour le header > le comportement quand on scroll.

**Comment by bedhed** [comment]
Pour les tags, il faut effectivement réduire la visibilité. Par contre quand je parlais d'admin, c'est pour moi toute la Ruche Mama + les modérateurs du réseau, donc plusieurs dizaines d'utilisateurs.
L'utilisation principale étant Practishare https://github.com/lrqdo/lrqdo-plugin-discourse/issues/34
Oki pour la catégorie N.

**Comment by ekkans** [comment]
Ok donc seulement la catégorie n est affichée sur la pré-prod

**Comment by discolaura** [comment]
Oui ! # Point Prio
+1 pour la catégorie N (plus contextuelle) que la catégorie N-1
@bedhed

**Comment by jeremie-baboukhian** [comment]
après discussion avec @bedhed  et @discolaura 
On vire les tags en front

**Comment by bedhed** [comment]
Par contre, laisser l'edition dispo en cliquant sur le crayon (dispo aux modos et admin uniquement)

**Comment by ekkans** [comment]
C'est bon sur la pré-prod.

![screenshot 2016-12-14 19 19 45](https://cloud.githubusercontent.com/assets/88243/21195069/73679d1e-c232-11e6-89d3-488d469e273e.png)

Pour ce qui est de l'édition des tags disponible uniquement pour les modos et admins, je dois faire quelque chose ou ça peut se configurer dans l'admin @bedhed  ?
