### ISSUE TITLE
Design Mobile

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#18]

**Comment by jeremie-baboukhian** [comment]
**+1**
J'hésite dans la méthodologie de travail sur ce point.
Soit je corrige et améliore l'existant, soit je design from scratch.
Qu'en penses-tu ?
En terme de temps de travail ca revient au même pour moi, par contre pas sur que cela soit similaire pour @ekkans.
Let me know

**Comment by ekkans** [comment]
@MarzChew – je pense que ce qui serait bien c'est de ne pas toucher à l'html, mais juste au css

**Comment by jeremie-baboukhian** [comment]
True 
à m'assigner pls

**Comment by jeremie-baboukhian** [comment]
J'ai update le css de la pré-prod
