### ISSUE TITLE
Abonnement catégorie

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#19]
Cette feature est importante pour les power users et je pense qu'on peut caser le petit bouton discretement quelque part.
<img width="597" alt="screen shot 2016-11-29 at 12 11 53" src="https://cloud.githubusercontent.com/assets/1053676/20707792/28c1fb1c-b62d-11e6-8502-a3a7928292f3.png">

**Comment by discolaura** [comment]
Oui ! # Point Prio
@bedhed

**Comment by bedhed** [comment]
Poke @marzchew (c'est celui ci qui est important)

**Comment by jeremie-baboukhian** [comment]
👍

**Comment by ekkans** [comment]
Je l'affiche à nouveau sur la pré-prod. Tu peux toucher un peu au css si besoin @MarzChew (?). Et tu me diras si tu veux que je touche à l'html également un peu

![screenshot 2016-12-14 19 16 01](https://cloud.githubusercontent.com/assets/88243/21194895/eac885a4-c231-11e6-8f63-faf74f9a1031.png)

**Comment by bedhed** [comment]
Je peux vivre avec ça (le modifier n'est pas visible par l'utilisateur classique).

**Comment by jeremie-baboukhian** [comment]
Il faudrait rajouter une mention. Je design ca today

**Comment by jeremie-baboukhian** [comment]
done en live sur la prépod.
J'ai aussi revu les entêtes des catégories (très bien d'ailleurs à généraliser @discolaura et @bedhed )
https://lrqdo.sebastienbourdu.com/c/porteparoles

**Comment by bedhed** [comment]
@MarzChew
float: right ?
<img width="686" alt="screen shot 2016-12-27 at 10 48 13" src="https://cloud.githubusercontent.com/assets/1053676/21496891/07407b8e-cc22-11e6-828a-3e43e41d4779.png">

**Comment by jeremie-baboukhian** [comment]
Perso je préfère à gauche car associé avec la catégorie 

Envoyé depuis mon iPhone
