### ISSUE TITLE
Abonnement Topic

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#20]
Moins important, mais si faisable discretement.
<img width="586" alt="screen shot 2016-11-29 at 12 13 22" src="https://cloud.githubusercontent.com/assets/1053676/20707808/465712a2-b62d-11e6-96d2-5a447fe2d8c4.png">

**Comment by ekkans** [comment]
Dupliqué de #1 (?)

**Comment by bedhed** [comment]
Nope, il y a 2 types : topic et category. Et je pense que c'est le category le plus utile.
(le topic se fait automatiquement).

**Comment by discolaura** [comment]
Oui ! # Point Prio
@bedhed

**Comment by jeremie-baboukhian** [comment]
Abonnement Topic > on laisse la gestion auto de discourse 
Pour les cats > je vais regarder ca

**Comment by ekkans** [comment]
@MarzChew – j'affiche quand même le bouton pour les topics comme sur la pré-prod actuellement ? Perso, cela me semble bien utile

![screenshot 2016-12-14 19 36 55](https://cloud.githubusercontent.com/assets/88243/21195624/d7f18004-c234-11e6-900e-60177181ed3c.png)

**Comment by bedhed** [comment]
à voir avec @MarzChew

**Comment by jeremie-baboukhian** [comment]
De mon point de vu, l'option sur les topics n'est pas nécessaires. Cela réintroduit de la complexité.
