### ISSUE TITLE
Citations sur nouvel éditeur

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#22]
Petit bug intermittent.
<img width="1212" alt="screen shot 2016-11-29 at 12 15 55" src="https://cloud.githubusercontent.com/assets/1053676/20707877/9fda0bae-b62d-11e6-9b29-7d5b142557aa.png">

**Comment by bedhed** [comment]
Qui fait aussi casser l'url et reste à la nav. Pas si négligeable.
![screen shot 2016-11-29 at 12 17 34](https://cloud.githubusercontent.com/assets/1053676/20707931/e328e024-b62d-11e6-945f-c1b9c459b744.png)

**Comment by ekkans** [comment]
C'est corrigé :)

**Comment by bedhed** [comment]
:+1:
