### ISSUE TITLE
Catégorie par défaut

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#23]
Il est très important de sélectionner la catégorie courante par défaut lors de la création d'un nouveau topic.
<img width="487" alt="screen shot 2016-11-29 at 12 18 37" src="https://cloud.githubusercontent.com/assets/1053676/20707953/1128d25e-b62e-11e6-9c5f-a6a083cd2ceb.png">

**Comment by discolaura** [comment]
Oui ! # Point Prio
@bedhed

**Comment by jeremie-baboukhian** [comment]
+1

**Comment by ekkans** [comment]
C'est bon sur la pré-prod :)

**Comment by bedhed** [comment]
Nickel !
