### ISSUE TITLE
Dernière activité

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#24]
Nous avons perdu les informations sur les activités récentes, ainsi la date affichée dans la liste est la date de création du topic. Difficile donc de comprendre l'ordre de la liste.
Now
<img width="645" alt="screen shot 2016-11-29 at 12 22 31" src="https://cloud.githubusercontent.com/assets/1053676/20708093/acfb13c2-b62e-11e6-8a39-7b96b0d15324.png">

On avait quelque chose de plus avancé dans le design
<img width="404" alt="screen shot 2016-11-29 at 12 24 25" src="https://cloud.githubusercontent.com/assets/1053676/20708119/cfa04910-b62e-11e6-9379-553d9552b044.png">

Version de base (plus réaliste ?)
<img width="242" alt="screen shot 2016-11-29 at 12 25 16" src="https://cloud.githubusercontent.com/assets/1053676/20708145/ef0d077a-b62e-11e6-93ff-ea37d617db0d.png">

**Comment by ekkans** [comment]
Je te ping un peu @MarzChew sur les issues où j'ai besoin de ton avis :)

**Comment by jeremie-baboukhian** [comment]
On en est où de l'implémentation des derniers reply ? Définitive abandonnée ?
Concernant la gestion de l'heure de publication, plus elle est peut-être avancée pour avoir une lecture plus humaine mieux c'est.
Priorité moyenne pour moi

**Comment by bedhed** [comment]
@MarzChew je n'ai pas bien compris ton retour.

**Comment by jeremie-baboukhian** [comment]
<img width="837" alt="capture d ecran 2017-02-28 a 16 45 46" src="https://cloud.githubusercontent.com/assets/1162156/23412389/a6f0b13c-fdd5-11e6-885b-f68a2310626f.png">
Suite à notre discussion avec @Biof J'ai décidé de privilégier la date du dernier reply sur la home.
à intégrer si possible du façon prioritaire

**Comment by bedhed** [comment]
:+1: Nice !
