### ISSUE TITLE
Nombre de vues

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#25]
Je ne sais pas si c'est important sur la topic list, mais c'est dommage de l'avoir nulle part.
<img width="242" alt="screen shot 2016-11-29 at 12 25 16" src="https://cloud.githubusercontent.com/assets/1053676/20708167/10bb48b4-b62f-11e6-84ce-b3ae8198c87b.png">
Si on met les comptes de clic sur les liens, il me parait logique d'avoir les comptes de vues. Mais peut-être qu'il faut aller dans l'autre sens et simplifier encore plus.

**Comment by ekkans** [comment]
Qu'en penses-tu @MarzChew ? :)

**Comment by discolaura** [comment]
@bedhed tu me diras où cela est-il visible dans la nouvelle version :)
sur les 3 métadata je serais d'avis d'en conserver 1 max, "nb reply" ou "last activity"

**Comment by jeremie-baboukhian** [comment]
J'ai un avis mitigé sur cette question.
Pour le user cela ne me semble pas une info primordiale.
Du coup plutôt pour les admins non ?
Pourriez-vous préciser l'usage, fréquence… ?

**Comment by bedhed** [comment]
Ok pour ne pas afficher les vues.
