### ISSUE TITLE
User card messy

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#26]
Now
<img width="591" alt="screen shot 2016-11-29 at 12 27 50" src="https://cloud.githubusercontent.com/assets/1053676/20708240/628b720e-b62f-11e6-990b-edf66018e97c.png">

Discourse
<img width="604" alt="screen shot 2016-11-29 at 12 28 20" src="https://cloud.githubusercontent.com/assets/1053676/20708247/66485ccc-b62f-11e6-8e0d-0866043a6045.png">

**Comment by ekkans** [comment]
Peut-être qu'on peut juste modifier un peu le css @MarzChew ?

**Comment by jeremie-baboukhian** [comment]
pour moi ca je note.
Je ne peux pas assigner les taches @bedhed pourrais-tu le faire pour moi.
