### ISSUE TITLE
Manque icone "réponse" devant le count

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#28]
Now
<img width="649" alt="screen shot 2016-11-29 at 12 32 32" src="https://cloud.githubusercontent.com/assets/1053676/20708383/ebacd1c2-b62f-11e6-9395-bfadf2557843.png">

Dans les emails discourse
<img width="639" alt="screen shot 2016-11-29 at 12 32 10" src="https://cloud.githubusercontent.com/assets/1053676/20708375/e0d5d49c-b62f-11e6-9b7c-8ac938ef5913.png">

**Comment by jeremie-baboukhian** [comment]
+1 manque la bulle

**Comment by ekkans** [comment]
C'est bon sur la pré-prod :)

**Comment by ekkans** [comment]
@bedhed – je n'ai pas les droits pour fermer les issues Github. Je te laisserai le faire ?

**Comment by bedhed** [comment]
My mistake. Thx
