### ISSUE TITLE
Mes préférences

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#29]
Now
<img width="663" alt="screen shot 2016-11-29 at 12 33 19" src="https://cloud.githubusercontent.com/assets/1053676/20708416/135e5e8e-b630-11e6-99e8-583536b6313e.png">

Discourse
<img width="827" alt="screen shot 2016-11-29 at 12 33 27" src="https://cloud.githubusercontent.com/assets/1053676/20708418/1839666a-b630-11e6-8478-bdba15e619c6.png">

**Comment by ekkans** [comment]
J'ai mis le design de Discourse

![screenshot 2016-12-01 11 54 05](https://cloud.githubusercontent.com/assets/88243/20791379/06205374-b7bd-11e6-9fac-c4374eae299c.png)

**Comment by bedhed** [comment]
Perfect !
