### ISSUE TITLE
Unread count sur "À lire ensuite"

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#3]
<img width="677" alt="screen shot 2016-11-29 at 11 12 45" src="https://cloud.githubusercontent.com/assets/1053676/20705894/1b0590e0-b625-11e6-9063-a114a98e3c88.png">
Pastilles à améliorer ou à supprimer.

`<a href="/t/partage-de-la-valeur-2-bzz-special-votre-avis/583/6" class="badge badge-notification unread" title="vous avez 3 messages non lus sur ce sujet">3</a>`

**Comment by jeremie-baboukhian** [comment]
Ca va pas du tout ca effectivement.
On les avait supprimées sur la version de dev.
Pourrait-on faire de même sur la prod ?

**Comment by ekkans** [comment]
Je les avais affiché sur la prod car il me semblait que tu les voulais vraiment @bedhed (?). On peut juste les cacher en css en tout cas

**Comment by jeremie-baboukhian** [comment]
Lovely :D

**Comment by ekkans** [comment]
Je te laisse toucher au css @MarzChew ? car je ne sais pas ce que tu veux faire

**Comment by jeremie-baboukhian** [comment]
Je regarde ca quand j’ai minute.
Plus tôt la semaine prochaine car je suis en déplacement jusqu’en fin de semaine.
J.

**Comment by jeremie-baboukhian** [comment]
à m'assigner pls

**Comment by jeremie-baboukhian** [comment]
done 
display : none;
krkkr
