### ISSUE TITLE
Reply to messy

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#32]
<img width="443" alt="screen shot 2016-11-29 at 12 44 32" src="https://cloud.githubusercontent.com/assets/1053676/20708723/9ac0d324-b631-11e6-84c8-f194ed9323ae.png">

**Comment by ekkans** [comment]
Je te laisse modifier le css @MarzChew ? :)

**Comment by jeremie-baboukhian** [comment]
vous en pensez quoi ?
https://lrqdo.sebastienbourdu.com/t/test-medium-like-editor-smile/628/5

**Comment by ekkans** [comment]
Cool @MarzChew :)
