### ISSUE TITLE
Reply to cassé avec nouvel éditeur

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#33]
Lorsque j'utilise le bouton **reply to**, le nouvel éditeur ne l'indique pas et ce n'est pas enregistré lors du post.

**Comment by ekkans** [comment]
J'ai l'impression que c'est bon. C'est le comportement normal de Discourse de ne pas indiquer le nom à la première réponse ?

![screenshot 2016-12-01 11 51 00](https://cloud.githubusercontent.com/assets/88243/20791308/90ed094e-b7bc-11e6-8731-a648ca392e8d.png)

![screenshot 2016-12-01 11 48 33](https://cloud.githubusercontent.com/assets/88243/20791235/48306ac0-b7bc-11e6-8bd2-ee1f37cbe0ca.png)

**Comment by bedhed** [comment]
Fair !
