### ISSUE TITLE
Intégration Practishare/Lattice

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#34]
Navigation/Sommaire de poste 2D pour capitalisation du savoir et des pratiques.
![screen shot 2016-11-29 at 17 31 42](https://cloud.githubusercontent.com/assets/1053676/20718661/bc90f07e-b659-11e6-8d63-a521a142c006.png)

**Comment by ekkans** [comment]
Largeur corrigée :)

![screenshot 2016-12-01 11 46 29](https://cloud.githubusercontent.com/assets/88243/20791143/db0df2dc-b7bb-11e6-91d4-3f76f5f3d9e2.png)

**Comment by bedhed** [comment]
:+1:
