### ISSUE TITLE
Images déformées sur la home

### ISSUE THREAD

**Issue by jeremie-baboukhian** [lrqdo/plugin-discourse#35]
<img width="683" alt="capture d ecran 2016-11-30 a 10 55 00" src="https://cloud.githubusercontent.com/assets/1162156/20747755/96018670-b6eb-11e6-8d3a-17829497411c.png">

**Comment by ekkans** [comment]
C'est corrigé

```css
  max-width: 190px;
  max-height: 190px;
```

**Comment by jeremie-baboukhian** [comment]
Fix thx
