### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#36]
Les textes de la nouvelle interface sont statiques... on est donc bloqué sur le Français. 
<img width="624" alt="screen shot 2016-12-02 at 12 29 39" src="https://cloud.githubusercontent.com/assets/1053676/20832545/0782bc38-b88b-11e6-956c-9c98bc47a628.png">

**Comment by jeremie-baboukhian** [comment]
[request Info] @ekkans on a besoin de tes lumières la dessus.
Difficulté de 1 à 5 ?

**Comment by ekkans** [comment]
Genre 2-4h à faire en comptant l'éditeur

**Comment by jeremie-baboukhian** [comment]
@discolaura @bedhed  good pour vous ?

**Comment by bedhed** [comment]
en utilisant l'internationalisation native @ekkans ?

**Comment by ekkans** [comment]
Oui @bedhed – vous pourrez gérer les valeurs depuis l'admin de Discourse
