### ISSUE TITLE
Scroll aux flèches sur emojis

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#37]
Lorsque je tappe 🍔 je veux pouvoir descendre dans le menu d'emojis avec les flèches.
<img width="368" alt="screen shot 2016-12-05 at 16 52 12" src="https://cloud.githubusercontent.com/assets/1053676/20891517/3d58f160-bb0b-11e6-8230-2104060cb5fa.png">

**Comment by jeremie-baboukhian** [comment]
+1
