### ISSUE TITLE
Menu des catégories plus zoli

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#38]
Dans le nouvel éditeur, le sélecteur de catégorie est améliorable 😉 
<img width="389" alt="screen shot 2016-12-05 at 16 53 13" src="https://cloud.githubusercontent.com/assets/1053676/20891568/6c943b42-bb0b-11e6-89bb-dcf93ff0c926.png">

**Comment by jeremie-baboukhian** [comment]
@ekkans dans quel mesure pouvons-nous reprendre le module d'origine et customizer le css ?

**Comment by ekkans** [comment]
J'ai amélioré ça. Je te laisse toucher un peu au css si besoin @MarzChew 
Aussi, on peut facilement ajouter d'autres informations (celles de ce JSON http://lrqdo.sebastienbourdu.com/categories.json)

![screenshot 2016-12-14 19 11 35](https://cloud.githubusercontent.com/assets/88243/21194751/55c01f94-c231-11e6-8d5d-f56a344d8f57.png)

**Comment by bedhed** [comment]
Extra ! Merci \o/ (je laisse @MarzChew fermer)

**Comment by jeremie-baboukhian** [comment]
Je traite tout ca asap.
Merci pour les retours.
