### ISSUE TITLE
Preview Emojis dans listes

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#39]
Apparemment les listes n'affichent pas les emojis, et la syntaxe diverge aussi.
Exemple de topic affiché sur la home:
---
<img width="406" alt="screen shot 2016-12-05 at 17 00 15" src="https://cloud.githubusercontent.com/assets/1053676/20891969/b24e15c6-bb0c-11e6-9d61-730361474156.png">

---

**Comment by discolaura** [comment]
@bedhed tu m'expliqueras, je n'ai pas bien compris ce qui ne fonctionne pas :)

**Comment by jeremie-baboukhian** [comment]
[Request] Un screenshot ?
à moins que @ekkans sache déjà de quoi il s'agit

**Comment by bedhed** [comment]
C'est un screenshot ;-)

**Comment by ekkans** [comment]
(Le screenshot dans le contexte @MarzChew )
![screenshot 2016-12-13 14 40 31](https://cloud.githubusercontent.com/assets/88243/21142443/76756e28-c142-11e6-981e-e09fc5b82b8c.png)

**Comment by jeremie-baboukhian** [comment]
Ah ok le listing d'article. je comprends mieux. 
LOL 🍭

**Comment by jeremie-baboukhian** [comment]
@ekkans ca vient de peut-être de là ?
Si on déclare les fonts d'émoji ca peut peut-être solutionner le problème ?
https://bitsofco.de/the-new-system-font-stack/


body {  
  font-family: -apple-system, 
               BlinkMacSystemFont, 
               "Segoe UI", 
               Roboto, 
               Helvetica,
               Arial,
               sans-serif,
               "Apple Color Emoji",  /* Emojis*/
               "Segoe UI Emoji", /* Emojis*/
               "Segoe UI Symbol"; /* Emojis*/
}

**Comment by jeremie-baboukhian** [comment]
@ekkans as-tu pu essayer ?

**Comment by ekkans** [comment]
C'est bon, c'est corrigé :)
![screenshot 2017-01-08 23 11 00](https://cloud.githubusercontent.com/assets/88243/21754012/1b3ec32c-d5f8-11e6-8896-605f8d6980e3.png)
