### ISSUE TITLE
Badge de Catégories à couleur dynamique

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#4]
Utiliser la feature Discourse pour gérer les couleurs des badges de Catégorie.
<img width="516" alt="screen shot 2016-11-29 at 11 28 02" src="https://cloud.githubusercontent.com/assets/1053676/20706314/f1e64798-b626-11e6-9133-cb4a756e1b5d.png">
<img width="1310" alt="screen shot 2016-11-29 at 11 27 28" src="https://cloud.githubusercontent.com/assets/1053676/20706315/f1e68b5e-b626-11e6-9d7b-b69202d5d8c0.png">

**Comment by jeremie-baboukhian** [comment]
Ok +1 
@ekkans

**Comment by ekkans** [comment]
C'est bon. Il faudra penser à changer les couleurs sur la prod avant de déployer la nouvelle version du plugin (cc @bedhed )

**Comment by bedhed** [comment]
Assigned to me. Poke @discolaura par sécurité:
TODO: change colors of categories on discourse to...

**Comment by bedhed** [comment]
@ekkans can you provide the #colors we need to configure ?

**Comment by ekkans** [comment]
Yes @bedhed :)
Couleur du fond : #AFE1E1
Couleur du texte : #056E7D
