### ISSUE TITLE
Users disparus du menu déroulant de la Search

### ISSUE THREAD

**Issue by discolaura** [lrqdo/plugin-discourse#40]
**Issue:**
Il n'est plus possible de trouver des users via le menu déroulant de la Search.
Nous avons entre autre bâti un annuaire interne sur cette fonctionnalité.
Cf tuto : https://forums.laruchequiditoui.fr/t/407

**Expérience utilisateur initiale:**
si je tape le vrai nom ou le pseudo de quelqu'un, dès 3 ou 4 caractères, les profils des users correspondants apparaissent en bas du menu déroulant avec les résultats.

**Visuels meta.discourse:**
![capture d ecran 2016-12-12 a 18 18 08](https://cloud.githubusercontent.com/assets/15192958/21109036/95c44fde-c097-11e6-9702-8fb0af9a3941.png)
![capture d ecran 2016-12-12 a 18 18 30](https://cloud.githubusercontent.com/assets/15192958/21109035/95c39210-c097-11e6-9835-e5e909aed3eb.png)

**Comment by jeremie-baboukhian** [comment]
Cela me semble important aussi.
Néanmoins serait-il possible de préciser l'usage (fréquence…) ?
Cela nous permettrait de statuer plus facilement sur son niveau de priorité.

**Comment by discolaura** [comment]
l'usage dépend de la présence ou non de la fonctionnalité...
Cet annuaire a vocation a remplacer un ficher spreadsheet qui est la référence actuelle donc consulté très régulièrement par les équipes pour trouver un contact.
Une fois que Discourse sera prêt, le plan c'est de killer ce spreadsheet et de promouvoir l'usage des profils discourse et de la search à la place.

**Comment by ekkans** [comment]
C'est corrigé sur la pré-prod @discolaura :)

![screenshot 2016-12-20 14 55 19](https://cloud.githubusercontent.com/assets/88243/21353048/83681dec-c6c4-11e6-9f2b-d90284ad49c9.png)
