### ISSUE TITLE
New Editeur : quelles options sont conservées pour structurer le contenu d'un post ?

### ISSUE THREAD

**Issue by discolaura** [lrqdo/plugin-discourse#41]
Dans Discourse aujourd'hui, il est possible de:
- créer des barres horizontales entre 2 paragraphes
ex : https://forums.laruchequiditoui.fr/t/370
- masquer du texte, que l'user fait apparaître en cliquant sur un petit triangle.
ex : https://forums.laruchequiditoui.fr/t/548

Ces fonctionnalités ne sont pas clées pour l'usage social/communautaires, mais le sont pour l'usage wiki / tuto qui est dans les plans de plusieurs équipes:
- Tutos par les équipes internes pour les salariés (équipement IT, dashboards BI, process HR...)
- Tutos de l'équipe Support sur l'utilisation de la webapp LRQDO (pas-à-pas techniques qui pourront être cherchables et consultables depuis notre backoffice)

**Comment by bedhed** [comment]
poke @ekkans pour l'évaluation et l'avis.
@MarzChew pour l'avis.

**Comment by ekkans** [comment]
J'ai ajouté la barre horizontale sur la pré-prod car c'était rapide à faire.

Pour ce qui est du petit triangle pour masquer le texte. J'ai testé et ça fonctionne d'ajouter le markdown dans le nouvel éditeur. C'est possible que cela fonctionne seulement pour les choses simples, mais par exemple l'exemple suivant fonctionne. ``[details=Résumé]Test[/details]``
Est-ce suffisant ? Et peut-être qu'on peut passer en mode avancé (= retour sur l'éditeur de base) pour ce genre de choses ? (cc @discolaura )

**Comment by bedhed** [comment]
@discolaura je pense que passer à l'éditeur de base est acceptable pour les power users qui font de la doc. Tu en penses quoi ?

**Comment by discolaura** [comment]
Hello ! merci bcp @ekkans  👍  je me range à ton avis @bedhed que ca passe très bien sur l'éditeur de base pour les power users.

**Comment by jeremie-baboukhian** [comment]
D'accord avec ca.
On a l'éditeur advance pour ca.
Done du coup ?
