### ISSUE TITLE
No reaction on clicking "créer un sujet"

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#42]
Lorsque j'ouvre l'éditeur puis que je le referme, puis j'essaie de réouvrir, rien ne se passe. Rien de verbeux dans la console à part un warning.
<img width="1433" alt="screen shot 2016-12-15 at 10 04 53" src="https://cloud.githubusercontent.com/assets/1053676/21217720/f79ecf50-c2ad-11e6-92a3-3b131f514d4e.png">

**Comment by ekkans** [comment]
Bug corrigé
