### ISSUE TITLE
Clic dans recherche puis rien

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#43]
Souvent lorsque je clique un résultat de la recherche il ne se passe rien: le dropdown se ferme mais je ne change pas de page. Au bout de 2/3 essais ça passe... Très frustrant.
Une idée @ekkans . Quelqu'un d'autre a expérimenté ce comportement ?

**Comment by ekkans** [comment]
Je pense que c'est bon. Vous me direz si ça se reproduit :)
