### ISSUE TITLE
Clic Count on Link size

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#47]
<img width="680" alt="screen shot 2017-01-12 at 10 31 51" src="https://cloud.githubusercontent.com/assets/1053676/21884160/6c803876-d8b2-11e6-99bf-2e72b3d3604f.png">

**Comment by ekkans** [comment]
Je les ai modifiés de la façon suivante 
![screenshot 2017-01-13 19 01 24](https://cloud.githubusercontent.com/assets/88243/21940052/c61f3f92-d9c2-11e6-97b8-982292dc8161.png)
