### ISSUE TITLE
Badge deformé

### ISSUE THREAD

**Issue by jeremie-baboukhian** [lrqdo/plugin-discourse#48]
<img width="391" alt="capture d ecran 2017-01-12 a 13 48 23" src="https://cloud.githubusercontent.com/assets/1162156/21890407/dadfc4e2-d8cd-11e6-9e64-7d5ce4b0b88a.png">

Bizarre ca ?
@ekkans

**Comment by ekkans** [comment]
@MarzChew – tu veux que cela ressemble à quoi ? Un rond j'imagine ? De la même couleur ? Bref dis-moi ou sinon tu peux aussi changer le css directement

**Comment by ekkans** [comment]
Je les ai modifiés de la façon suivante 
![screenshot 2017-01-13 19 01 24](https://cloud.githubusercontent.com/assets/88243/21940052/c61f3f92-d9c2-11e6-97b8-982292dc8161.png)
