### ISSUE TITLE
Mentions are not displayed right with new editor

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#49]
When mentioning in the new editor, it displays like this in the old
<img width="617" alt="screen shot 2017-01-13 at 10 19 32" src="https://cloud.githubusercontent.com/assets/1053676/21924549/f7357400-d979-11e6-8ea4-1ca47a83caf1.png">
Meaning it's not really a mention, it's a link to the user profile.
As a result, the user card does not work, and I'm wondering if the notification does...
That's what we want (but don't have)
<img width="1053" alt="screen shot 2017-01-13 at 10 18 50" src="https://cloud.githubusercontent.com/assets/1053676/21924587/1d6b7214-d97a-11e6-95cd-daa4fcb334ec.png">

**Comment by ekkans** [comment]
Normalement c'est bon maintenant (en pré-prod et aussi prod)
