### ISSUE TITLE
Category list page

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#5]
Même si l'on exposera pas la fonctionnalité à tous les utilisateurs, nous avons besoin d'une solution pour réduire la liste des catégories à gauche.
<img width="245" alt="screen shot 2016-11-29 at 11 30 18" src="https://cloud.githubusercontent.com/assets/1053676/20706382/5b9895ce-b627-11e6-9c27-aa90dc1487cd.png">

**Comment by discolaura** [comment]
Oui ! # Point prio
@bedhed

**Comment by bedhed** [comment]
Poke @marzchew

**Comment by jeremie-baboukhian** [comment]
J'ai vu je réfléchie à ça.

**Comment by jeremie-baboukhian** [comment]
C'est pas du tout évident de trouver une solution.
Si on met en place un système d'accordéon du coup on affiche uniquement les catégories parentes.
Conséquence les catégories enfants les plus utilisées n'apparaitront plus. 
Ce qui me posent problème…

**Comment by jeremie-baboukhian** [comment]
sur https://discuss.flarum.org/ quand on clique sur more on affiche une page dédiée au listing…

**Comment by bedhed** [comment]
@MarzChew je comprends, je pense que montrer la hierarchie des catégories et sous-catégories dans le menu de gauche doit être abandonné. L'idée d'envoyer vers la liste des catégories au clic sur "more" me semble propre.
@discolaura est-ce acceptable pour toi :
- menu de gauche = top 5 sous-catégories sans visualisation des parents
- page catégories accessible par "voir plus" (et ensuite, version propre de [cette page](https://lrqdo.sebastienbourdu.com/categories) )
Dans tous les cas on fait notre maximum, coté admin, pour supprimer les niveaux de catégorie.

**Comment by jeremie-baboukhian** [comment]
So @discolaura ?
@ekkans (on a une page native comme ca sur discource, non ?

**Comment by ekkans** [comment]
(@MarzChew c'est celle-ci https://lrqdo.sebastienbourdu.com/categories )

**Comment by bedhed** [comment]
y'a une option pour désactiver la colonne de droite sur cette page (ici la colonne passe en dessous). À mon avis elle est viable cette page une fois corrigée.

**Comment by bedhed** [comment]
J'ai changé le titre et la milestone ;-)
