### ISSUE TITLE
Créer une catégorie

### ISSUE THREAD

**Issue by discolaura** [lrqdo/plugin-discourse#51]
Plus de "bouton" accessible pour créer une catégorie.
A voir pour quel niveaux ou groupes d'utilisateurs cette fonctionnalité est disponible.

Aujourd'hui pour créer une catégorie il faut connaître l'URL de la page listant les catégories, qui est la seule à ma connaissance à proposer un petit bouton pour le faire.
https://forums.laruchequiditoui.fr/categories

Cette page n'est pas accessible depuis la home.

**Comment by ekkans** [comment]
@discolaura – la page /categories est maintenant accessible via le lien *voir plus* de la sidebar (voir issue #5) (déployé seulement sur la préprod pour l'instant)
