### ISSUE TITLE
Répondre à 

### ISSUE THREAD

**Issue by jeremie-baboukhian** [lrqdo/plugin-discourse#58]
<img width="603" alt="capture d ecran 2017-02-28 a 17 08 18" src="https://cloud.githubusercontent.com/assets/1162156/23413308/8fc5b50e-fdd8-11e6-8c1c-8c790e5b8b46.png">

Qu'en pensez-vous ?
@Biof @bedhed

**Comment by bedhed** [comment]
Pourquoi pas :+1:
