### ISSUE TITLE
Icone enveloppe devant les conversations privées

### ISSUE THREAD

**Issue by bedhed** [lrqdo/plugin-discourse#9]
La différence est visible dans la notif
<img width="327" alt="screen shot 2016-11-29 at 11 44 18" src="https://cloud.githubusercontent.com/assets/1053676/20706813/597a84b2-b629-11e6-8782-e9baad8ad145.png">

Mais pas dans la conversation
<img width="744" alt="screen shot 2016-11-29 at 11 44 26" src="https://cloud.githubusercontent.com/assets/1053676/20706818/5ffdc15a-b629-11e6-91cd-5b34ad149507.png">

**Comment by ekkans** [comment]
C'est corrigé :)

**Comment by bedhed** [comment]
![screen shot 2016-12-01 at 4 10 50 pm](https://cloud.githubusercontent.com/assets/1053676/20798902/d24b24d8-b7e0-11e6-9326-3c14fca76a3e.png)
Pas certain, cette notif était un topic public. Et on a perdu le bold sur l'auteur ? Probablement des conflits de version.

**Comment by ekkans** [comment]
Hum en effet tous les topics ont l'enveloppe.. je vais regarder ça

**Comment by ekkans** [comment]
Corrigé sur la pré-prod
